### ISSUE TITLE
Db missing

### ISSUE THREAD

**Issue by siddhantrimal** [iamnaran/phpProject-#1]
# Almost there...

A great approach to show CRUD with PHP. [Currently](https://github.com/iamnaran/phpProject-/commit/273961ce30d257056a7a4c4b1a625d5d19e043c1), Db: project cannot be found in a potential user's localhost as set up in [dbconfig\config.php](https://github.com/iamnaran/phpProject-/blob/273961ce30d257056a7a4c4b1a625d5d19e043c1/dbconfig/config.php). It would be much more effective if you'd also upload the database. 

Please fix by committing Db in `phpProject-\_database\yourDbName.db` as an export.

**Comment by iamnaran** [comment]
I dun have that DB.. 😆  or anything related to this project :D

**Comment by siddhantrimal** [comment]
hahaha well that's a shame :D

**Comment by iamnaran** [comment]
Done .. check readme (y) 😆
